### ISSUE TITLE
[CRASH] Crash using TAIGA-based weapon

### ISSUE THREAD

**Issue by Utildayael** [TeamFRM/TAIGA#126]
Was using a rapier with vibranium blade and went to attack a mob... and crashed to desktop. :(

I think it's TAIGA but if not please let me know and I can log under Tinkers.

```
Description: Unexpected error

java.lang.ArithmeticException: / by zero
	at com.sosnitzka.taiga.traits.TraitHeroic.damage(TraitHeroic.java:20)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:629)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:572)
	at slimeknights.tconstruct.library.utils.ToolHelper.attackEntity(ToolHelper.java:568)
	at slimeknights.tconstruct.library.tools.ToolCore.onLeftClickEntity(ToolCore.java:212)
	at net.minecraftforge.common.ForgeHooks.onPlayerAttackTarget(ForgeHooks.java:963)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78764_a(PlayerControllerMP.java:526)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1452)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Here's the full log:
http://pastebin.com/DkkSwhKS

Cheers!

**Comment by Utildayael** [comment]
Reloading game... tried again... yup. 100% repro. Same error and crash to desktop when attacking with the weapon.

Weapon in question:

**Rapier**
Blade: Vibranium
Cross Guard: Manyullan
Tool Rod: Nihilum

**Comment by Flabort** [comment]
There's already a fix on the way [in this commit](https://github.com/TeamFRM/TAIGA/commit/b874a41abb8a82c801130e54ef28520431c1c8e1) so the next version should fix this error.

**Comment by Utildayael** [comment]
Excellent. It certainly was odd it did that on my new tool but a server buddy used an old tool that had leveled up a few times and swapped in a Vibranium blade and his was fine. 

Thanks for the quick fix!

**Comment by Flabort** [comment]
Don't thank me, I'm just a fan of the mod :P

**Comment by Utildayael** [comment]
Whoooops. I shouldn't Git by email. :)

**Comment by IdleGandalf** [comment]
Closing this, already fixed.
